### ISSUE TITLE
Flip option

### ISSUE THREAD

**Issue by danigmx1** [MiSTer-devel/Arcade-DigDug_MiSTer#9]
Is it possible to implement an option for image flipping, so it's possible to play on a CCW rotated CRT?

**Comment by JimmyStones** [comment]
This should now work in the latest version (20220317) - please test and close the issue if it's all good 👍

**Comment by danigmx1** [comment]
Working flawlessly, sorry I haven't closed this until now.

**Comment by JimmyStones** [comment]
> 

Nice, cheers :D
